name: Build & Release (SLSA3)
on:
  push:
    tags:
      - '1.0.0.0-beta.*' # beta标签触发
  workflow_dispatch: # 手动触发

permissions:
  contents: write
  attestations: write
  id-token: write

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout source
        uses: actions/checkout@v4

      - name: Setup JDK 21
        uses: actions/setup-java@v4
        with:
          java-version: '21'
          distribution: 'temurin'

      - name: Setup Gradle
        uses: gradle/actions/setup-gradle@v4

      - name: Make gradlew executable
        run: chmod +x gradlew

      - name: Build mod jar
        run: ./gradlew build

      - name: Upload build artifact
        uses: actions/upload-artifact@v4
        with:
          name: mod-jar
          path: build/libs/*.jar

      # 拿到jar文件列表，解决attest不支持通配符问题
      - name: Get jar path
        id: jar_file
        run: echo "path=$(ls build/libs/*.jar)" >> $GITHUB_OUTPUT

      - name: Generate SLSA3 Artifact Attestation
        uses: actions/attest-build-provenance@v1
        with:
          subject-path: ${{ steps.jar_file.outputs.path }}

      - name: Create GitHub Release
        uses: softprops/action-gh-release@v2
        with:
          prerelease: true
          files: build/libs/*.jar
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
